# Generated by Django 3.2.14 on 2022-08-03 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mainapp', '0011_remove_estadia_forma_pago'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoReservaRestaurante',
            fields=[
                ('id_estado', models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='id_estado')),
                ('estado', models.CharField(max_length=12, verbose_name='estado')),
            ],
        ),
        migrations.CreateModel(
            name='TipoRestaurante',
            fields=[
                ('id_tipo_restaurante', models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='id_tipo_restaurante')),
                ('descripcion', models.CharField(max_length=12, verbose_name='descripcion')),
            ],
        ),
        migrations.CreateModel(
            name='TurnosReserva',
            fields=[
                ('id_turno', models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='id_turno')),
                ('horario', models.CharField(max_length=12, verbose_name='horario')),
            ],
        ),
        migrations.CreateModel(
            name='Restaurante',
            fields=[
                ('id_restaurante', models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='id_restaurante')),
                ('nombre', models.CharField(max_length=12, verbose_name='nombre')),
                ('cant_mesas', models.IntegerField(verbose_name='cantidad_mesas')),
                ('tipo_restaurante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurantes.tiporestaurante', verbose_name='tipo_restaurante')),
            ],
        ),
        migrations.CreateModel(
            name='ReservaRestaurante',
            fields=[
                ('id_reserva', models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='id_reserva')),
                ('estadia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.estadia', verbose_name='servicio')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurantes.estadoreservarestaurante', verbose_name='servicio')),
                ('restaurante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurantes.restaurante', verbose_name='servicio')),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurantes.turnosreserva', verbose_name='servicio')),
            ],
        ),
    ]
