# Generated by Django 3.2.14 on 2022-08-04 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantes', '0002_auto_20220803_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurante',
            name='precio_base',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4, verbose_name='precio_base'),
            preserve_default=False,
        ),
    ]
