# Generated by Django 3.2.14 on 2022-08-04 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantes', '0003_restaurante_precio_base'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurante',
            name='nombre',
            field=models.CharField(max_length=25, verbose_name='nombre'),
        ),
    ]
