# Generated by Django 3.2.14 on 2022-08-04 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_remove_estadia_forma_pago'),
        ('restaurantes', '0004_alter_restaurante_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservarestaurante',
            name='estadia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.estadia', verbose_name='estadia'),
        ),
        migrations.AlterField(
            model_name='reservarestaurante',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurantes.estadoreservarestaurante', verbose_name='estado'),
        ),
        migrations.AlterField(
            model_name='reservarestaurante',
            name='restaurante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurantes.restaurante', verbose_name='restaurante'),
        ),
        migrations.AlterField(
            model_name='reservarestaurante',
            name='turno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurantes.turnoreserva', verbose_name='turno'),
        ),
    ]
