# Generated by Django 3.2.14 on 2022-08-04 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantes', '0006_reservarestaurante_fecha_reserva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservarestaurante',
            name='fecha_reserva',
            field=models.DateField(verbose_name='fecha_reserva'),
        ),
    ]
