# Generated by Django 3.2.14 on 2022-08-08 19:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActividadUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.DateTimeField(null=True, verbose_name='Login')),
                ('logout', models.DateTimeField(null=True, verbose_name='Logout')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Actividad',
                'verbose_name_plural': 'Actividades',
                'db_table': 'actividades',
                'ordering': ['usuario', 'creado'],
            },
        ),
    ]
