# Generated by Django 3.0.8 on 2022-07-23 20:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('habitaciones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('huespedes', '0005_auto_20220713_1732'),
    ]

    operations = [
        migrations.CreateModel(
            name='Descuentos',
            fields=[
                ('id_descuento', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True, verbose_name='id_descuento')),
                ('descripcion', models.CharField(max_length=12, verbose_name='descripcion')),
                ('estado', models.CharField(max_length=12, verbose_name='estado')),
                ('multiplicador', models.DecimalField(decimal_places=3, max_digits=4, verbose_name='multiplicador')),
            ],
            options={
                'verbose_name': 'Descuento',
                'verbose_name_plural': 'Descuentos',
                'db_table': 'descuentos',
                'ordering': ['id_descuento'],
            },
        ),
        migrations.CreateModel(
            name='Estadia',
            fields=[
                ('id_estadia', models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='id_estadia')),
                ('estado', models.CharField(max_length=10, verbose_name='estado')),
                ('fecha_inicio', models.DateField(verbose_name='fecha_inicio')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='fecha_fin')),
                ('cantidad_dias', models.IntegerField(verbose_name='cantidad_dias')),
                ('forma_pago', models.CharField(max_length=10, verbose_name='forma_pago')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modificado')),
                ('habitacion', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='habitaciones.Habitacion', verbose_name='habitacion')),
                ('huesped', models.ManyToManyField(to='huespedes.Huesped', verbose_name='Huespedes')),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'Estadia',
                'verbose_name_plural': 'Estadias',
                'db_table': 'estadias',
                'ordering': ['id_estadia'],
            },
        ),
    ]
