# Generated by Django 3.0.8 on 2022-07-24 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoEstadia',
            fields=[
                ('nro_estado', models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='nro_estado')),
                ('estado', models.CharField(max_length=10, verbose_name='estado')),
            ],
            options={
                'verbose_name': 'Estado',
                'verbose_name_plural': 'Estados',
                'db_table': 'estados_estadia',
                'ordering': ['estado'],
            },
        ),
        migrations.CreateModel(
            name='FormasPago',
            fields=[
                ('id_formaPago', models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='id_formaPago')),
                ('descripcion', models.CharField(max_length=10, verbose_name='descripcion')),
            ],
            options={
                'verbose_name': 'FormaPago',
                'verbose_name_plural': 'FormasPago',
                'db_table': 'forma_pago',
                'ordering': ['descripcion'],
            },
        ),
        migrations.AlterField(
            model_name='estadia',
            name='estado',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='mainapp.EstadoEstadia', verbose_name='estado'),
        ),
        migrations.AlterField(
            model_name='estadia',
            name='forma_pago',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='mainapp.FormasPago', verbose_name='forma_pago'),
        ),
    ]
