# Generated by Django 3.0.8 on 2022-07-26 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20220725_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descuentos',
            name='estadia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.Estadia', verbose_name='estadia'),
        ),
    ]
