# Generated by Django 3.0.8 on 2022-07-24 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20220724_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadia',
            name='forma_pago',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.FormasPago', verbose_name='forma_pago'),
        ),
    ]
