# Generated by Django 3.0.8 on 2022-07-26 19:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0003_auto_20220726_1024'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estadoestadia',
            options={'ordering': ['nro_estado'], 'verbose_name': 'Estado', 'verbose_name_plural': 'Estados'},
        ),
        migrations.AlterModelOptions(
            name='formaspago',
            options={'ordering': ['id_formaPago'], 'verbose_name': 'FormaPago', 'verbose_name_plural': 'FormasPago'},
        ),
        migrations.AlterField(
            model_name='estadia',
            name='user',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='usuario'),
        ),
    ]
