# Generated by Django 3.0.8 on 2022-07-24 22:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20220724_1855'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadosDecuentos',
            fields=[
                ('nro_estado', models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='nro_estado')),
                ('estado', models.CharField(max_length=10, verbose_name='estado')),
            ],
            options={
                'verbose_name': 'Estado',
                'verbose_name_plural': 'Estados',
                'db_table': 'estados_descuento',
                'ordering': ['estado'],
            },
        ),
        migrations.AddField(
            model_name='descuentos',
            name='fecha_creacion',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='fecha_creacion'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='descuentos',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.EstadosDecuentos', verbose_name='estado'),
        ),
    ]
