# Generated by Django 3.2.14 on 2022-08-01 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_reglamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reglamento',
            name='retiro_anticipado',
            field=models.IntegerField(verbose_name='tasa'),
        ),
    ]
