# Generated by Django 3.0.8 on 2022-07-24 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_auto_20220724_1912'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estadosdecuentos',
            options={'ordering': ['estado'], 'verbose_name': 'Estado Descuento', 'verbose_name_plural': 'Estados Decuentos'},
        ),
    ]
