# Generated by Django 3.2.14 on 2022-08-01 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_alter_reglamento_retiro_anticipado'),
    ]

    operations = [
        migrations.AddField(
            model_name='estadia',
            name='penalizacion',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=2, verbose_name='penalizacion'),
        ),
    ]
