# Generated by Django 3.2.14 on 2022-08-01 21:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0009_alter_estadia_penalizacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadia',
            name='penalizacion',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='penalizacion'),
        ),
        migrations.AlterField(
            model_name='estadia',
            name='user',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='usuario'),
        ),
        migrations.AlterField(
            model_name='reglamento',
            name='retiro_anticipado',
            field=models.DecimalField(decimal_places=2, max_digits=3, verbose_name='tasa'),
        ),
    ]
