# Generated by Django 3.2.14 on 2022-08-02 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_auto_20220801_1816'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estadia',
            name='forma_pago',
        ),
    ]
