# Generated by Django 3.2.14 on 2022-08-08 16:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0014_remove_estadia_user_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='estadia',
            name='user_update',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mainapp_estadia_updated', to=settings.AUTH_USER_MODEL, verbose_name='Usuario_updated'),
        ),
    ]
