# Generated by Django 3.2.14 on 2022-08-08 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0016_alter_estadia_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadia',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creado'),
        ),
    ]
