# Generated by Django 3.0.8 on 2022-06-26 23:15

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Huesped',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni_huesped', models.IntegerField(validators=[django.core.validators.MinValueValidator(1000000)], verbose_name='Dni')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=255, verbose_name='Apellido')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha_nacimiento')),
                ('pais', models.CharField(max_length=20, verbose_name='Pais')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Huesped',
                'verbose_name_plural': 'Huespedes',
                'db_table': 'huespedes',
            },
        ),
    ]
