# Generated by Django 3.0.8 on 2022-07-25 21:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Huesped',
            fields=[
                ('dni', models.CharField(max_length=9, primary_key=True, serialize=False, verbose_name='Dni')),
                ('nombre', models.CharField(max_length=25, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=25, verbose_name='Apellido')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha_nacimiento')),
                ('pais', models.CharField(max_length=25, verbose_name='Pais')),
                ('direccion', models.CharField(default=None, max_length=25, verbose_name='Direccion')),
                ('telefono', models.CharField(default=None, max_length=14, verbose_name='Telefono')),
                ('mail', models.EmailField(default=None, max_length=40, verbose_name='Email')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Huesped',
                'verbose_name_plural': 'Huespedes',
                'db_table': 'huespedes',
            },
        ),
    ]
