# Generated by Django 3.0.8 on 2022-07-08 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huespedes', '0002_auto_20220626_2017'),
    ]

    operations = [
        migrations.RenameField(
            model_name='huesped',
            old_name='dni_huesped',
            new_name='dni',
        ),
        migrations.AddField(
            model_name='huesped',
            name='direccion',
            field=models.CharField(default=None, max_length=25, verbose_name='Direccion'),
        ),
        migrations.AddField(
            model_name='huesped',
            name='mail',
            field=models.EmailField(default=None, max_length=40, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='huesped',
            name='telefono',
            field=models.CharField(default=None, max_length=14, verbose_name='Telefono'),
        ),
        migrations.AlterField(
            model_name='huesped',
            name='apellido',
            field=models.CharField(max_length=25, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='huesped',
            name='nombre',
            field=models.CharField(max_length=25, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='huesped',
            name='pais',
            field=models.CharField(max_length=25, verbose_name='Pais'),
        ),
    ]
