# Generated by Django 3.0.8 on 2022-07-11 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huespedes', '0003_auto_20220708_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='huesped',
            name='dni',
            field=models.CharField(max_length=9, verbose_name='Dni'),
        ),
    ]
