# Generated by Django 3.2.14 on 2022-08-08 13:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('huespedes', '0003_alter_huesped_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='huesped',
            name='user_update',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_update', to=settings.AUTH_USER_MODEL, verbose_name='Usuario_modificacion'),
        ),
        migrations.AlterField(
            model_name='huesped',
            name='user',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
