# Generated by Django 3.0.8 on 2022-07-13 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huespedes', '0004_auto_20220711_1626'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='huesped',
            name='id',
        ),
        migrations.AlterField(
            model_name='huesped',
            name='dni',
            field=models.CharField(max_length=9, primary_key=True, serialize=False, verbose_name='Dni'),
        ),
    ]
