# Generated by Django 3.2.14 on 2022-08-08 13:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('huespedes', '0004_auto_20220808_1009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='huesped',
            name='user_update',
        ),
        migrations.AlterField(
            model_name='huesped',
            name='user',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
