# Generated by Django 3.2.14 on 2022-08-08 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('huespedes', '0006_auto_20220808_1033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='huesped',
            name='user_update',
        ),
    ]
