# Generated by Django 3.2.14 on 2022-08-08 17:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('huespedes', '0009_alter_huesped_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='huesped',
            name='user_update',
        ),
        migrations.AlterField(
            model_name='huesped',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creado'),
        ),
        migrations.AlterField(
            model_name='huesped',
            name='user',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
