# Generated by Django 3.0.8 on 2022-04-13 16:40

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='Contenido'),
        ),
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=models.CharField(max_length=150, unique=True, verbose_name='URL amigable'),
        ),
        migrations.AlterField(
            model_name='page',
            name='visible',
            field=models.BooleanField(verbose_name='¿Visible?'),
        ),
    ]
