# Generated by Django 3.0.8 on 2022-06-16 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20220413_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='orden',
            field=models.IntegerField(default=1, verbose_name='Orden'),
            preserve_default=False,
        ),
    ]
