# Generated by Django 3.0.8 on 2022-07-25 21:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mainapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoReserva',
            fields=[
                ('nro_estado', models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='nro_estado')),
                ('estado', models.CharField(max_length=10, verbose_name='estado')),
            ],
            options={
                'verbose_name': 'Estado Reserva',
                'verbose_name_plural': 'Estados Reservas',
                'db_table': 'estados_reserva',
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id_servicio', models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='id_servicio')),
                ('servicio', models.CharField(max_length=12, verbose_name='servicio')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='precio')),
                ('accesorios', models.CharField(max_length=50, verbose_name='accesorios')),
                ('maximo_diario', models.IntegerField(verbose_name='maximo_diario')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'db_table': 'servicios',
            },
        ),
        migrations.CreateModel(
            name='ReservaServicio',
            fields=[
                ('id_reserva', models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='id_reserva')),
                ('fecha_reserva', models.DateField(verbose_name='fecha_reserva')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modificado')),
                ('estadia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Estadia', verbose_name='estadia')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios.EstadoReserva', verbose_name='estado')),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'Reserva Servicio',
                'verbose_name_plural': 'Reservas Servicios',
                'db_table': 'reservas_servicio',
                'ordering': ['id_reserva'],
            },
        ),
    ]
