# Generated by Django 3.2.14 on 2022-07-31 23:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0002_auto_20220726_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservaservicio',
            name='servicio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='servicios.servicio', verbose_name='servicio'),
            preserve_default=False,
        ),
    ]
