# Generated by Django 3.0.8 on 2022-07-23 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipohabitacion',
            name='cantidad_ambientes',
            field=models.IntegerField(verbose_name='cantidad_ambientes'),
        ),
    ]
