# Generated by Django 3.0.8 on 2022-07-23 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('habitaciones', '0002_auto_20220723_1721'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoHabitacion',
            fields=[
                ('nro_estado', models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='nro_estado')),
                ('estado', models.CharField(max_length=10, verbose_name='estado')),
            ],
            options={
                'verbose_name': 'Estado',
                'verbose_name_plural': 'Estados',
                'db_table': 'estados',
            },
        ),
        migrations.AlterField(
            model_name='habitacion',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='habitaciones.EstadoHabitacion', verbose_name='estado'),
        ),
    ]
