# Generated by Django 3.0.8 on 2022-07-24 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habitaciones', '0003_auto_20220723_1753'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='estadohabitacion',
            table='estados_habitacion',
        ),
    ]
